#debug: true

siggi:
  login:
    controller:
      provider: ghcom
      scope: user:email,public_repo,write:public_key,write:gpg_key,write:repo_hook,read:org

  signup:
    admins: admin

  connect:
    ghcom:
      oauth2:
        clientId: 123456789abcdefgh #zaas-Localhost in orga 'siggi-ci'
        clientSecret: '123456789123456789abcdefghabcdefgh' # we use 'ticks' here, because 'clientSecret' sometimes contains 'yaml-sensitive-tokens'

  deploykeys:
    enable-preprocessing: true
    comment: ghcom-it-at-localhost

  services:
    github:
      deploykey:
        title: ghcom-it-at-localhost
      webhook:
        username: localUser
        password: secret
        hookUrl: https://your.hookendpoint.tld/hooks


management:
  port: 9090
  security:
    enabled: false

spring:

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource

  thymeleaf:
    mode: LEGACYHTML5

flyway:
  enabled: true
